[versions]
assertj = "3.25.3"
mockito = "5.11.0"
jackson = "2.17.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

[bundles]
mockito = ["mockito-core", "mockito-junit"]
